### ISSUE TITLE
0.9.3 errors

### ISSUE THREAD

**Issue by transat** [patriciogonzalezvivo/ofxStreetView#2]
Hi. I'm new to openframeworks and c++. I was wondering if much work would need to be done to this addon to make it work with of 0.9.3?
On OSX10.11 using Xcode 7.3, having used the projector generator and embedded both the ofxStreetView and ofxXmlSettings addons, I'm getting the following errors:

In **ofApp.h**:
`Field type 'ofxStreetView' is an abstract class.`

More specifically this seems to relate to:
```
"Unimplemented pure virtual method 'getTexture' in 'ofxStreetView' 
"Unimplemented pure virtual method 'isUsingTexture' in 'ofxStreetView' 
```

In **main.cpp**:
`No matching function for call to 'ofRunApp'`

Cheers

**Comment by mattfelsen** [comment]
Hey @transat, I haven't used this addon or tested this, but the issue you're running into relates to a change on openFrameworks with version 0.9. You should be able to get this compiling by...

1. chaging `getTextureReference()` to `getTexture()` in `ofxStreetView`
2. adding `bool isUsingTexture() { return true; }` to `ofxStreetView`

Hopefully that's enough to get you up & running?

**Comment by mattfelsen** [comment]
Actually, you may have to add a `const` version of `getTexture()` as well...

**Comment by transat** [comment]
Cheers Matt. I've changed every occurrence of getTextureReference() to getTexture() and added the isUsingTexture function but have no real idea how or where to add the const version of getTexture(). I'm literally just starting out with C++ and openFrameworks. I should probably start off with something simpler!

**Comment by mattfelsen** [comment]
Yea, `const` is sort of a tricky thing that you usually don't have to worry about (for a while, at least :smile: ). Don't worry, you'll get this! Try adding this to the header file...

```
const ofTexture& getTexture() const {
	return getTexture();
}
```

If that doesn't work, you can also try copy-and-pasting the getTexture() declaration (in the header file) and definition (in the cpp file) but add the `const` keyword in the 2 places I did, i.e. you will need both a "regular" version and a `const` version of `getTexture()`

**Comment by transat** [comment]
Thanks again! Adding `const ofTexture& getTexture() const {return getTexture();}` directly below the existing `ofTexture&  getTexture();` in ofxStreetView.h did progress things...

I'm now getting the following error: 

> 'Unimplemented pure virtual method 'isUsingTexture' in 'ofxStreetView'.

The ofxStreetView header contains this line:     `bool isUsingTexture(){return true;};`

I didn't do the second change you had suggested (copying and pasting the definition) as the new error does not mention getTexture anymore. But for reference sake, in the cpp file, would the following be the definition of getTexture?

```
ofTexture& ofxStreetView::getTexture(){
    if(!panoFbo.isAllocated()){
        panoFbo.allocate(getWidth(),getHeight());
    }

    return panoFbo.getTexture();
}
```

**Comment by mattfelsen** [comment]
@transat you are so close! Just gave this a shot, and got this running. I didn't notice that `isUsingTexture()` also needs to be `const`, so try modifying it as such (notice the `const` keyword after the function name):

`bool		isUsingTexture() const { return true; }`


![screen shot 2016-03-31 at 8 46 34 am](https://cloud.githubusercontent.com/assets/2334552/14176131/74316df0-f71d-11e5-810c-ab52305b82a2.png)
![screen shot 2016-03-31 at 8 47 19 am](https://cloud.githubusercontent.com/assets/2334552/14176132/7441a288-f71d-11e5-9179-c28c0e6d622f.png)

Hopefully that does the trick for you – let me know if it works!

@patriciogonzalezvivo seeing this app running brought back so many memories :)

**Comment by patriciogonzalezvivo** [comment]
Hi! Sorry I have been out for a while. And I haven't try OF 0.9 yet. : S

Thanks @transat for your efforts I'm really looking forward for the PR!

@mattfelsen my friend!!! I was remembering the same thing! I was showing you this crazy experiment in the middle of Thesis Studio : ) Good times!! Thanks so much for helping @transat

**Comment by transat** [comment]
@mattfelsen Darn. I had tried `const bool isUsingTexture() const { return true; }` but that hadn't worked.
Almost there but to get rid of two other errors:
```
'width' is a protected member of 'ofImage_<unsigned char>'
'height' is a protected member of 'ofImage_<unsigned char>'
```
I also had to change:
`panoImages.at(i).draw(x*panoImages.at(i).width, y*panoImages.at(i).height);`
to `panoImages.at(i).draw(x*panoImages.at(i).getWidth(), y*panoImages.at(i).getHeight());` 

Don't know if that was the right fix but it seems to be working now! And looks great.

@patriciogonzalezvivo No effort of mine – it was all Matt's doing as you can see. But I will definitely do my bit and send you a PR in the next couple of days. Love your work, btw.

**Comment by mattfelsen** [comment]
@transat ah yes, sorry, I forgot to mention that too. Your fix is correct! `width` and `height` became private members of `ofTexture` and instead need the getter functions like you found. All of this happened with some under-the-hood changes in OF 0.9.

For reference, you can see the functions that need to be implemented for an `ofBaseHasTexture` subclass in the `ofBaseTypes` header file to see specifically where `const` needs to be used (you can ignore the `virtual` keyword):
https://github.com/openframeworks/openFrameworks/blob/475595e551b9da641d78ffdf8012cdf15da556ba/libs/openFrameworks/types/ofBaseTypes.h#L155-L166

Cheers, glad you got it working! Also, welcome to the wonderful world of openFrameworks and C++! Most of the time you won't have to worry about details like this, but it's good to get a bit of exposure :smile:

**Comment by transat** [comment]
Apologies @mattfelsen and @patriciogonzalezvivo . I got sidetracked this week and didn't get around to making the changes which I see have now been made. Thanks again for your help.
